### ISSUE TITLE
cinnamon-spices

### ISSUE THREAD

**Issue by klavs** [linuxmint/mint-design#4]
There is a site (web interface) for Cinnamon themes, applets, desklets and extensions. As far as I know, users can access these spices using cinnamon-settings. What are the advantages of providing a web interace for spices over providing access to them only through cinnamon-settings?
In other words: What is the reason why cinnamon-spices exist?

**Comment by Sirikon** [comment]
I think that having a web version of the Cinnamon Spices is good for spreading themes, applets, desklets and extensions, this way people can have a link to show to other people some interesting stuff

**Comment by klavs** [comment]
Thanks! That sounds like a perfectly valid argument. This answers the main question - cinnamon-spices should still be used and incorporated (linked) somewhere in the main site.

Aside from that, I'd argue that this is not the best way possible to spread a spice, because user must download a spice and then manually extract it into the correct directory. I would say that it would be better to have some kind of specific archive format (like JAR for Java apps) and a specific app that installs the spice into the "correct" directory without user actually knowing what the "correct" directory actually is. Let's call it a *spice* file, for example.

**Comment by Sirikon** [comment]
Exactly!, I think the best approach for this is implement a behaviour similar to, for example, magnet links in torrent clients:

Those links are like this:
```
magnet:?xt=urn:sha1:PDAQRAOQQRYS76MRZJ33LK4MMVZBDSCL
```
And torrent clients like Transmission or uTorrent can open those links, and then add it to the download queue.

So what about a Cinnamon Spice link?

```
cinnamonspice:?sid=2938294&st=theme
```

Just an idea :smile:

**Comment by dalcde** [comment]
To answer the original question, cinnamon-spices exists for a variety of reasons. First is historical - in the beginning, cinnamon-settings couldn't download spices. cinnamon-spices is also the only place where you could upload a spice, see the description, give comments etc.

I think it is worth keeping as a last resort for downloading a spice. Otherwise, if, say, a GNOME Extension developer wants to make reference to some cinnamon extension, they would have to install the whole cinnamon in order to download the spice.

Ultimately, I think it is worth keeping, but we might change the way how it works. Maybe we put a huge banner asking people to use cinnamon-settings to install; rename the "Download" button as "Download source" so tthat people think they shouldn't be pressing that button etc. We should also integrate the functionalities into cinnamon-settings.

**Comment by JosephMcc** [comment]
One good reason for the actual site to exist is the comments. It gives users a place to give feedback to the spices devs if they are having an issue or for feature requests.

**Comment by Sirikon** [comment]
Those are functionalities that would be great to have in the desktop application, and keep both application and webpage working

**Comment by klavs** [comment]
I like the idea that cinnamon-spices are used by developers. Also, I like the idea that user does not need to go to web page to give feedback or questions. (I know, it could be a tricky line - settings for configuration vs settings for communication)

**Comment by klavs** [comment]
In summary, cinnanin-spices should still exist as a web interface. Primary users would be developers not casual users.
